version: '2'
services:
  mysql:
    container_name: realworld
    restart: always
    image: mysql:latest

    environment:
      MYSQL_ROOT_PASSWORD: 'pAssw8rd'

      MYSQL_USER: 'nestjsrealworld'
      MYSQL_PASS: 'nestjsrealworld'
    volumes:
      - realworld-datavolume:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  realworld-datavolume:


